HoagieClub/plan

backend/majors/REL.yaml, backend/minors/REL.yaml
Added in a new yaml for the Religion minor requirements given here: https://religion.princeton.edu/undergraduate/religion-minor.
(apologies if I did anything in the process wrong)
=> new religion yaml

backend/minors/EUS.yaml
Added new yaml for the European Studies (EUS) minor (https://ecs.princeton.edu/minor/).
=> new euro studies minor yaml

frontend/app/calendar/page.tsx, frontend/package-lock.json, frontend/package.json
Added feature: when a user loads up Calendar the semester that should be preselected should be the current semester.
=> Automatic Semester in Calendar

frontend/app/calendar/page.tsx, frontend/package-lock.json, frontend/package.json
=> Revert "Automatic Semester in Calendar"

backend/minors/MAT.yaml
Wrote .yaml file for the mathematics minor based off https://ua.princeton.edu/fields-study/departmental-majors-degree-bachelor-arts/mathematics.
=> Mathematics Minor YAML File

backend/minors/ENE.yaml
sorry for this abomination the andlinger center seems to think everything is a sustainable energy course
=> Sustainable energy minor

backend/minors/APC.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-66/applied-and-computational-mathematics
thank you!
=> applied + computational math minor yaml

backend/minors/ART.yaml
First draft of Art History YAML
=> First draft of Art History YAML

backend/minors/ARA.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-64/arabic-language-minor
- https://ua.princeton.edu/fields-study/minors/arabic-language
=> added ARA yaml file

backend/minors/HEB.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-69/hebrew-language-minor
- Added Hebrew language minor YAML
=> Added HEB language minor yaml

backend/minors/ART.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-65/archaeology-minor
- Added ART.yaml for Archaeology Minor
=> Added Archaeology Minor YAML

backend/minors/JDS.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-71/judaic-studies-minor
- Added Judaic Studies minor
=> Added JDS YAML file

backend/minors/HART.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-33/history-of-art-minor-yaml
- Linear: https://linear.app/hoagie/issue/DEV-65/archaeology-minor
- Re-insert History of ART minor YAML that was overwritten in this [PR](https://github.com/HoagieClub/plan/commit/b4fd09fca0d35f114c8c85f861d85b15fc6f2cf7)
=> Re-insert history of art minor YAML

backend/minors/ENE.yaml
was crashing while loading yaml into meeting, fixed now to load successfully
=> indentation fix ene minor

backend/minors/MAT.yaml
**References**
- Linear: N/A
- I was unable to add the MAT.yaml file to the database, and this seems to be a "malfunction error?" that is the result of some formatting issues that I just fixed.
=> fixed some formatting issues in the MAT.yaml file

backend/minors/PHY.yaml
=> Engineering Physics Minor

backend/minors/ARA.yaml, frontend/components/UserSettings.tsx
**References**
- Linear: [DEV-64](https://linear.app/hoagie/issue/DEV-64/arabic-language-minor)
- Added [Arabic Language Minor](https://ua.princeton.edu/fields-study/minors/arabic-language)
=> Lucyc arabic yaml

backend/minors/LAS.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-72/latin-american-studies-minor
- Added [Latin American Studies minor](https://ua.princeton.edu/fields-study/minors/latin-american-studies)
=> Latin American Studies Minor

backend/minors/AAS.yaml
**References**
- Linear: African American Studies Minor
- Added AAS minor
@issacli-0821
=> AAS yaml update

backend/minors/NES.yaml, frontend/components/UserSettings.tsx
**References**
- Linear: https://linear.app/hoagie/issue/DEV-79/near-eastern-studies-minor
- Added [Near Eastern Studies minor](https://ua.princeton.edu/fields-study/departmental-majors-degree-bachelor-arts/near-eastern-studies)
=> add: Near Eastern Studies minor

backend/minors/FRE.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-68/french-and-italian-minor
- Added [French minor](https://ua.princeton.edu/fields-study/departmental-majors-degree-bachelor-arts/french-and-italian)
=> French Minor

backend/minors/HART.yaml, backend/minors/HOA.yaml
**References**
- Linear: [DEV-33](https://linear.app/hoagie/issue/DEV-30/add-yaml-files-for-new-minors)
- Added [History of Art minor](https://ua.princeton.edu/fields-study/minors/history-art)
=> Issac history of art addition

backend/minors/CGS.yaml
**References**
- Linear:
- _Add your proposed changes here_
=> Cognitive Science Minor Yaml

backend/degrees/BSE.yaml
**References**
- Linear: None
- Changed Seven Total Courses requirement to use all distributions
=> Added distribution requirement for Seven Total Courses

frontend/components/Navbar.tsx, frontend/store/modalSlice.ts
**References**
- Linear: https://linear.app/hoagie/issue/DEV-47/tutorial-modal-on-load-up
- Updated pr request for modal
=> Updated Tutorial Modal

frontend/app/about/page.tsx
**References**
- Linear: https://linear.app/hoagie/issue/DEV-61/hoagieplan-update-about-page
- Added Team Leads and Contributors to About Page
=> Update About Page

frontend/app/calendar/CalendarCard.tsx, frontend/store/calendarSlice.ts, frontend/types.d.ts
Fixed calendar logic errors and transparency for choice classes added.
=> Calendar Logic and Transparency

frontend/app/calendar/CalendarSearchItem.module.scss, frontend/app/calendar/CalendarSearchItem.tsx
**References**
- Linear: https://linear.app/hoagie/issue/DEV-109/graying-out-add-button-when-course-is-inserted
- when rendering CalendarSearchItem, check to see if course is selected by user. If so, grey it out and remove the hover effect/onclick event
=> DEV-109: Graying Out Add Button When Course is Inserted

frontend/components/Hero.tsx
**References**
- Linear: DEV-88
- Fixed whitespace at bottom of screen by making height of background match screen height.
=> Fixed whitespace at bottom of screen

frontend/components/Search.tsx, frontend/store/searchSlice.ts, frontend/types.d.ts
**References**
- Linear: DEV-48
- Added the Clear Searches button to the search component
=> added cleared searches button

backend/majors/ORF.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-126/orf-electives-update
- Updated electives for ORF
=> DEV-126: ORF Electives Update

backend/majors/CBE.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-125/cbe-thesis-update
- Updated IW req for CBE
=> DEV-125: Updated IW for CBE

backend/majors/NEU.yaml, backend/minors/NEU.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-124/neu-electives-update
- Updated electives for NEU major and minor
=> DEV-124: NEU Electives Update

backend/majors/PSY.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-123/psy-prerequisites-update
- Updated Core prerequisites for PSY major
=> DEV-118: PSY Prerequisites Update

backend/majors/PHY.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-121/phy-unnamed-requirements
- Added names and relevant description to requirements that did not have those fields
=> DEV-121: PHY Unnamed Requirements

backend/majors/MAE.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-119/mae-math-requirement
- Updated MAE math requirement as described [here](https://ua.princeton.edu/fields-study/departmental-majors-degree-bachelor-science-engineering/mechanical-and-aerospace)
=> DEV 119: Updated MAE math requirement

backend/majors/ENG.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-120/eng-distribution-requirement-update
- Updated English distribution requirements based on [ENG website](https://english.princeton.edu/undergraduate/courses/courses-distribution-requirement)
=> DEV-120: Updated distribution requirements for ENG major

backend/degrees/AB.yaml, backend/degrees/BSE.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-127/double-counting-cd-for-ab-and-bse
- Updated double counting rules for CD
=> DEV-127: Double Counting CD For AB and BSE

frontend/app/calendar/CalendarSearch.tsx
**References**
- Linear: https://linear.app/hoagie/issue/DEV-116/create-export-calendar-button
- Added "Export Calendar" button under Recent Searches
=> created export calendar button under recent searches

frontend/app/calendar/Calendar.css, frontend/app/calendar/SelectedCourses.module.css, frontend/app/calendar/page.tsx, frontend/components/TabbedMenu/TabbedMenu.module.css
**References**
- Linear: https://linear.app/hoagie/issue/DEV-139/div-sizes-in-calendar
Lined up the three sections in calendar.
=> DEV-139: Lining up the Calendar Section

backend/degrees/AB.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-136/fix-ab-completed-by-semester-field
- Remove `completed_by_semester` field for "Degree Progress'
=> DEV-136: Fix AB completed_by_semester Field

backend/minors/HOA.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-130/hoa-minor-yaml-fix
- Fix YAML formatting error by indenting
=> DEV-130: HOA Minor YAML Fix

backend/majors/MAT.yaml
**References**
- Linear: https://linear.app/hoagie/issue/DEV-128/mat-major-requirements
- Updated MAT major requirements
=> DEV-128: Updated MAT Major Requirements

backend/hoagieplan/api/search.py, frontend/components/Search.tsx, frontend/store/filterSlice.ts, frontend/types.ts
**References**
- Linear: [DEV-24](https://linear.app/hoagie/issue/DEV-24/hoagieplan-stackable-filters-distribution-area)
- Updated distribution search to support multiple distribution areas
Reference: [Old PR](https://github.com/HoagieClub/plan/pull/64)
=> DEV-24: Stackable Filters (Distribution Areas)

backend/minors/SML.yaml
**References**
- Linear: [DEV-157](https://linear.app/hoagie/issue/DEV-157/sml-minor-update)
- Updated electives for SML Minor
=> DEV-157: SML Minor Update

frontend/app/calendar/Calendar.scss, frontend/app/calendar/CalendarCard.tsx
**References**
- Linear: https://linear.app/hoagie/issue/DEV-135/reduce-font-size-for-calendar-card
- Decreased top and bottom padding of .calendar-card in _frontend/app/calendar/Calendar.scss_
- Decreased font size of time and capacity elements in _frontend/app/calendar/CalendarCard.tsx_
=> DEV-135 Reduce Font Size for Calendar Card

frontend/app/calendar/Calendar.scss, frontend/app/calendar/CalendarGrid.tsx
**References**
- Linear: https://linear.app/hoagie/issue/DEV-141/calendar-times-off-by-one
- Shift calendar times down by one
=> DEV-141: Calendar Times Off By One

backend/hoagieplan/api/dashboard/requirements.py
**References**
- Linear: https://linear.app/hoagie/issue/DEV-101/insert-courses-from-json
- Same as PR 70 but on the dev branch instead
=> DEV-101: Insert Courses from JSON

backend/config/urls.py, backend/hoagieplan/ical_generator.py, frontend/app/calendar/CalendarSearch.tsx, frontend/app/dashboard/Canvas.tsx, frontend/components/Widgets/Widget.tsx
**References**
- Linear: https://linear.app/hoagie/issue/DEV-129/add-functionality-to-calendar-button
- Added functionality to the export calendar button
=> DEV 129 - Add Functionality to Calendar Button

frontend/app/layout.tsx, frontend/components/ReviewMenu.tsx
**References**
- Linear: N/A
- Comment out `manifest.json`
- Added tbody tag to prevent hydration error
=> DEV-XX: Fix various Next.js issues

backend/majors/PSY.yaml
**References**
- Linear: [DEV-210](https://linear.app/hoagie/issue/DEV-210/psy-requirements)
- Fixed PSY prerequisites
=> DEV-210: Fixed PSY prerequisites

backend/minors/DAN.yaml
**References**
- Linear: [DEV-205](https://linear.app/hoagie/issue/DEV-205/dan-requirements)
- Fixed DAN requirements
=> DEV-205: Fixed DAN requirements

backend/majors/COS-BSE.yaml
**References**
- Linear: [DEV-206](https://linear.app/hoagie/issue/DEV-206/cos-major-theory-requirements)
- Add COS 330 to COS theory requirements
=> DEV-206: Add to COS theory reqs

backend/constants.py
**References**
- Linear: [DEV-207](https://linear.app/hoagie/issue/DEV-207/asl-as-foreign-language)
- Add ASL to satisfy foreign language requirements for AB
=> DEV-207: Add ASL as foreign language for AB

backend/majors/SPI.yaml
**References**
- Linear: [DEV-203](https://linear.app/hoagie/issue/DEV-203/spia-requirements)
- Updated SPIA electives to double count
=> DEV-203: Updated SPIA Electives to double count

backend/certificates/AAS.yaml, backend/certificates/LAC-CLA.yaml, backend/certificates/LAC-POR.yaml, backend/certificates/LAC-SPA.yaml, backend/certificates/RIS.yaml, frontend/components/UserSettings.tsx
**References**
- Linear: DEV-XX
- [List of certificates](https://odoc.princeton.edu/learning-curriculum/majors-minors)
- Remove certificates that have been removed from list in UserProfile
=> Removed certificates that have been phased out

backend/minors/PHY.yaml
**References**
- Linear: [DEV-220](https://linear.app/hoagie/issue/DEV-220/corrected-phy-minor)
- Corrected physics minor to count only physics classes that are 200 level or higher
=> DEV-220: Corrected PHY Minor

frontend/app/about/page.tsx
**References**
- Linear: DEV-256
- added self to team page
=> DEV-256: added Grace Ding to team page

frontend/app/about/page.tsx
**References**
- Linear: DEV 261: https://linear.app/hoagie/issue/DEV-261/add-gary-yang-as-a-contributor
- Added Gary Yang as a contributor
=> DEV-261: added gary as a contributor

frontend/app/about/page.tsx
- Linear: DEV-284
-Added Profile to Hoagie Plan Page
=> DEV-284: Added Albert Rho to Page

frontend/app/about/page.tsx
**References**
- Linear: DEV-260
- Added Phu Duong as a contributor
=> DEV-260: Added Phu Duong as a contributor
